// frontend/src/components/LoginForm.jsx
import React, { useState } from 'react';
import api from '../api';

const LoginForm = () => {
  const [form, setForm] = useState({ email: '', password: '' });

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await api.post('/auth/login', form);
      localStorage.setItem('token', response.data.token);
      // redirect to dashboard
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input type="email" name="email" value={form.email} onChange={handleChange} placeholder="Email" />
      <input type="password" name="password" value={form.password} onChange={handleChange} placeholder="Password" />
      <button type="submit">Login</button>
    </form>
  );
};

export default LoginForm;

// frontend/src/components/LoginForm.vue
<template>
    <form @submit.prevent="handleSubmit">
      <input type="email" v-model="form.email" placeholder="Email" />
      <input type="password" v-model="form.password" placeholder="Password" />
      <button type="submit">Login</button>
    </form>
  </template>
  
  <script>
  import api from '../api';
  
  export default {
    data() {
      return {
        form: {
          email: '',
          password: '',
        },
      };
    },
    methods: {
      async handleSubmit() {
        try {
          const response = await api.post('/auth/login', this.form);
          localStorage.setItem('token', response.data.token);
          this.$router.push('/'); // Redirect to the dashboard or home page
        } catch (error) {
          console.error(error);
        }
      },
    },
  };
  </script>
