// frontend/src/components/RegisterForm.jsx
import React, { useState } from 'react';
import api from '../api';

const RegisterForm = () => {
  const [form, setForm] = useState({ firstName: '', lastName: '', email: '', phoneNumber: '', password: '', role: 'buyer' });

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await api.post('/auth/register', form);
      // redirect to login or dashboard
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input type="text" name="firstName" value={form.firstName} onChange={handleChange} placeholder="First Name" />
      <input type="text" name="lastName" value={form.lastName} onChange={handleChange} placeholder="Last Name" />
      <input type="email" name="email" value={form.email} onChange={handleChange} placeholder="Email" />
      <input type="text" name="phoneNumber" value={form.phoneNumber} onChange={handleChange} placeholder="Phone Number" />
      <input type="password" name="password" value={form.password} onChange={handleChange} placeholder="Password" />
      <select name="role" value={form.role} onChange={handleChange}>
        <option value="buyer">Buyer</option>
        <option value="seller">Seller</option>
      </select>
      <button type="submit">Register</button>
    </form>
  );
};

export default RegisterForm;

// frontend/src/components/RegisterForm.vue
<template>
    <form @submit.prevent="handleSubmit">
      <input type="text" v-model="form.firstName" placeholder="First Name" />
      <input type="text" v-model="form.lastName" placeholder="Last Name" />
      <input type="email" v-model="form.email" placeholder="Email" />
      <input type="text" v-model="form.phoneNumber" placeholder="Phone Number" />
      <input type="password" v-model="form.password" placeholder="Password" />
      <select v-model="form.role">
        <option value="buyer">Buyer</option>
        <option value="seller">Seller</option>
      </select>
      <button type="submit">Register</button>
    </form>
  </template>
  
  <script>
  import api from '../api';
  
  export default {
    data() {
      return {
        form: {
          firstName: '',
          lastName: '',
          email: '',
          phoneNumber: '',
          password: '',
          role: 'buyer',
        },
      };
    },
    methods: {
      async handleSubmit() {
        try {
          await api.post('/auth/register', this.form);
          this.$router.push('/login'); // Redirect to login or dashboard
        } catch (error) {
          console.error(error);
        }
      },
    },
  };
  </script>
